services:
  postgres:
    image: 'postgres:alpine3.16'
    container_name: nexus_postgres
    hostname: postgres
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: mmcsnexus
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build:
      context: "./backend"
    container_name: nexus_backend
    hostname: backend
    environment:
      POSTGRES_URL: postgres:5432
      POSTGRES_DATABASE: mmcsnexus
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      GITHUB_CLIENT_ID: $GITHUB_CLIENT_ID
      GITHUB_CLIENT_SECRET: $GITHUB_CLIENT_SECRET
      BASE_URL: $BASE_URL

  client:
    image: node:20-alpine
    container_name: nexus_client
    working_dir: /app
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      # для hot reload в Docker Desktop/WSL
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
      BROWSER: "none"
      HOST: "0.0.0.0"
      PORT: "3000"
    command: sh -c "npm install && npm run start"
    ports:
      - 3000:3000

volumes:
  db-data:
